### ISSUE TITLE
Is there dotnetcore support coming up ? 

### ISSUE THREAD

**Issue by robvanpamel** [SolalPirelli/ThriftSharp#2]

**Comment by SolalPirelli** [comment]
I have it working locally (which also means the new `DispatchProxy` stuff can replace the annoying boilerplate `ThriftServiceImplementation`). I'll release a new version soon.

**Comment by robvanpamel** [comment]
thanks for this!

**Comment by SolalPirelli** [comment]
Version 5.0.0 has been released on NuGet, supporting both .NET Core and the full .NET Framework.

I'm closing this issue, but feel free to reopen it if you see something's wrong. Documentation on projects that support both frameworks is a bit shaky, so I may have forgotten to do something. :s

**Comment by SolalPirelli** [comment]
If you're using ThriftSharp in an UWP app, I'm afraid 5.0.0 will not work in Release mode - I can't figure out how to include the rd.xml file so it gets picked up properly. Working on it...

**Comment by SolalPirelli** [comment]
ThriftSharp 5.0.4 fixes the rd.xml problem. (5.0.1 through 5.0.3 were failed attempts at it, thus they've been unlisted)
