### ISSUE TITLE
Does it support binary as a special Thrift type?

### ISSUE THREAD

**Issue by Tuatan** [SolalPirelli/ThriftSharp#4]
According to [this](http://thrift.apache.org/docs/types), the Thrift also supports binary as a parameter type, does this library support that?

e.g, what is the way to define binary data. For example, I want to use the following type, but the parser throws ThriftParsingException: The type 'Byte' is an unknown value type.

```csharp
[ThriftStruct("Container")]
public class ThriftType
{
	[ThriftField(1, true, "data")]
	public byte[] Data { get; set; }
}
```

And the metadata for that type is:

```
struct Container {
 1: binary data
}
```

**Comment by SolalPirelli** [comment]
As [the wiki](https://github.com/SolalPirelli/ThriftSharp/wiki/Thrift-types-and-their-mappings) (which is, admittedly, not a great way to provide documentation...) notes, Thrift's `binary` is mapped to `sbyte[]` since Thrift's binary uses signed bytes (for Java compat).
