### ISSUE TITLE
Size of the byte[] returned by ThriftSerializer.Serialize

### ISSUE THREAD

**Issue by tranb3r** [SolalPirelli/ThriftSharp#7]
The size of the byte[] returned by ThriftSerializer.Serialize corresponds to the internal buffer capactity, instead of its actual length.
Is it done on purpose ?
In order to fix it, simply replace stream.GetBuffer with stream.ToArray in ThriftMemoryTransport.GetInternalBuffer.

**Comment by SolalPirelli** [comment]
I suppose I did this to avoid copying? But indeed having an incorrect length does not seem like a good idea.
Indeed using ToArray would fix this bug, though maybe one can build an `ArraySegment` (or `Span` on modern .NET) instead to have the right length without a copy?

**Comment by tranb3r** [comment]
As a client, I'm using ThriftSerializer.Serialize.
How could the client know the size of the serialized object ? This is all internal stuff...

**Comment by SolalPirelli** [comment]
Yes, I meant the serializer should be changed internally to either use ToArray or to return a segment/span. Sorry for the ambiguity.
